language: python

matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true
        - os: linux
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=py37   
    
sudo: required

install: 
  - pip3 install -r requirements.txt

script:
  - pytest